components:
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: 9d30d8e63ace49f579318f63a8f31be0189d6aaf
    type: git
  gmmlib:
    asset_name: gmmlib
    dest_dir: gmmlib
    type: git
    branch: master
    revision: intel-gmmlib-22.3.11
    repository: https://github.com/intel/gmmlib.git
  igc:
    asset_name: igc
    dest_dir: igc
    type: git
    branch: releases/igc-1.0.15610
    revision: igc-1.0.15610.11
    repository: https://github.com/intel/intelgraphicscompiler
  igsc:
    asset_name: igsc
    dest_dir: igsc
    type: git
    branch: master
    revision: V0.8.13
    repository: https://github.com/intel/igsc.git
    component_version: 183
  infra:
    branch: neo/releases/23.48
    dest_dir: infra
    fetch_tags: true
    revision: v5543.1382.2
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    dest_dir: kernels_bin
    type: git
    branch: kernels_bin
    revision: 2165-1170
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 552a3276a44e3255cf2a184acfc98123a43518b6
    type: git
  level_zero:
    asset_name: level_zero
    dest_dir: level_zero
    type: git
    branch: master
    revision: v1.15.1
    repository: https://github.com/oneapi-src/level-zero
  libva:
    asset_name: libva
    dest_dir: libva
    type: git
    branch: v2.2-branch
    revision: 2.2.0
    repository: https://github.com/intel/libva.git
  metrics-discovery:
    asset_name: metrics-discovery
    dest_dir: metrics/discovery
    type: git
    branch: master
    revision: metrics-discovery-1.12.168
    repository: https://github.com/intel/metrics-discovery.git
  metrics-library:
    asset_name: metrics-library
    dest_dir: metrics/library
    type: git
    branch: master
    revision: metrics-library-1.0.152
    repository: https://github.com/intel/metrics-library.git
  neo-clang-format:
    dest_dir: tools/clang-format
    type: git
    branch: clang-format
    revision: 15.0.6
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: d5d610ae2912b2c7f80baca382ba8a7b6efb1b95-2165
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-2165
version: '1'
